### ISSUE TITLE
guzzlehttp to be in require not require-dev in composer.json

### ISSUE THREAD

**Issue by shadiakiki1986** [varsitynewsnetwork/wordpress-rest-api-client#3]
`guzzlehttp/guzzle` is in `require-dev` in `composer.json`, but it should be in the `require` tag, e.g. the example in the readme wont run without it

**Comment by mrkrstphr** [comment]
Guzzle is a soft dependency. You can write your own adapter and use a different Http library, hence why it also appears in `suggest`. I will, however, update the installation instructions to explain this.
